name: publish docker image
on:
    push:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3
        
      - name: log in to docker hub
        uses: docker/login
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

       - name: extract metadata (tags,labels) for docker
         id: meta
         uses: docker/metadata
         with:
           images: megha_paliwal/try_that

       - name: Build and push docker image
         uses: docker/build-push-action
         with:
            context:
            push: true
            tags: ${{steps.meta.out}}    


 
 
