name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to DigitalOcean Container Registry
        run: echo ${{ secrets.DOCR_TOKEN }} | docker login -u ${{ secrets.DOCR_USERNAME }} --password-stdin registry.digitalocean.com

      - name: Build and push Docker image
        run: |
          docker build -t registry.digitalocean.com/<your-docr-namespace>/<your-image-name>:latest .
          docker push registry.digitalocean.com/<your-docr-namespace>/<your-image-name>:latest

 
